config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :groups do
    resources :comments
  end

  namespace :api do
    namespace :v1 do
       resources :users, only: [:index, :create, :show, :update, :destroy]
       resources :sessions, only:[:create]
       resources :groups, only: [:index]
    end
  end

  root "groups#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :review, presence:{message:"评论内容不能为空"}
  belongs_to :user
  belongs_to :group, counter_cache: true

  scope :recent, -> {order("created_at DESC")}
end

app/models/group.rb
class Group < ApplicationRecord
  validates :title, presence:{message:"请填写主题"}
  validates :city, presence:{message:"请填写举办地点"}
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :groups
  has_many :comments

   def user_name
     self.email.split("@").first
   end

   before_create :generate_authentication_token

   def generate_authentication_token
     self.authentication_token = Devise.friendly_token
   end
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ApplicationController

  attr_accessor :current_user
  protect_from_forgery with: :null_session

  before_action :destroy_session

  skip_before_action :verify_authenticity_token

  def destroy_session
    request.session_options[:skip] = true
  end

  def authenticate_user!
    token, options = ActionController::HttpAuthentication::Token.token_and_options(request)
    user_email = options.blank?? nil :options[:email]
    user = user_email && User.find_by(email: user_email)

    if user && ActiveSupport::SecurityUtils.secure_compare(user.authentication_token,token)
      self.current_user = user
    else
      return unauthenticated!
    end
  end

  def unauthenticated!
    api_error(status: 401)
  end

  def api_error(opts = {})
    render nothing: true, status: opts[:status]
  end
end

app/controllers/api/v1/groups_controller.rb
class Api::V1::GroupsController < Api::V1::BaseController

  before_action :authenticate_user!, only: [:index]

  def index
    @groups = Group.all
  end

end

app/controllers/api/v1/sessions_controller.rb
class Api::V1::SessionsController < Api::V1::BaseController

  def create
    @user = User.find_by(email: create_params[:email])
    if @user && @user.valid_password?(create_params[:password])
      sign_in :user, @user
    else
      return api_error(status: 401)
    end
  end


  private
  def create_params
   params.require(:user).permit(:email, :password)
 end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::V1::BaseController
  before_action :authenticate_user!, only:[:update]

  def show
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update_attributes(update_params)
  end

  private

  def update_params
    params.require(:user).permit(:name)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!,only:[:create,:destroy]

  def create
    @group= Group.find(params[:group_id])
    @comment = Comment.new(comment_params)
    @comment.group = @group
    @comment.user = current_user
     if @comment.save
    #@comment = @group.comments.create(params[:comment].permit(:review))

    redirect_to group_path(@group)
  else
    redirect_to group_path(@group)
    flash[:alert]='留言内容不能为空'
  end
  end

   private
   def comment_params
     params.require(:comment).permit(:user_id,:group_id,:review)
   end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!, only:[:new,:create,:edit,:update,:destroy]
  before_action :check_permission, only:[:edit,:update,:destroy]
  def index
    @groups = Group.all.order("created_at DESC").paginate(page: params[:page], per_page: 12)
    #Group.find_in_batches( :batch_size => 100) do |groups|
    #  if groups.present?
    #  @groups = groups
    #  @groups = @groups.sort_by(&:"created_at").reverse


    #end
  #end
end

 def show
   @group = Group.find(params[:id])
   @comments = @group.comments.recent.paginate(page: params[:page], per_page: 5)
   @comment = Comment.new
 end

  def new
    @group = Group.new
  end


 def create
   @group = Group.new(group_params)
   @group.user = current_user
   if @group.save
     redirect_to root_path
   else
     render :new
   end
 end

 def edit

 end

  def update

    if @group.update(group_params)
      redirect_to groups_path, notice: "Update Success"
    else
      render :edit
    end
  end

  def destroy

    @group.destroy
    redirect_to groups_path
  end

  private
  def group_params
    params.require(:group).permit(:title,:description,:city)
  end

  def check_permission
    @group = Group.find(params[:id])
    if current_user != @group.user
     redirect_to root_path, alert:"您没有操作权限"
   end
 end
 end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :authenticate_user!
  def index
    
  end
end

app/helpers/api/v1/base_helper.rb
module Api::V1::BaseHelper
end

app/helpers/api/v1/groups_helper.rb
module Api::V1::GroupsHelper
end

app/helpers/api/v1/sessions_helper.rb
module Api::V1::SessionsHelper
end

app/helpers/api/v1/users_helper.rb
module Api::V1::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = {alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice", "warning"
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
  def render_group_description(group)
    simple_format(group.description)
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_comment.html.erb
<div class="comment clearfix">
  <p>
  <%=comment.review %>
</p>
 <p>发表于
   <!-- <%#= time_ago_in_words(comment.created_at) %> Ago -->

 </p>
</div>

app/views/groups/_form.html.erb
<br>
<%= simple_form_for @group do |f| %>
<%= f.input :title, label: "主题" %>
<%= f.input :description, label:"活动内容" %>
<%= f.input :city, label:"地点" %>
<%= f.submit "确认", class:"btn btn-sm btn-primary",disable_with: "Submitting..." %>
<% end %>

app/views/groups/edit.html.erb
<div class="col-md-4 col-md-offset-4">
  <h3 class="text-center">编辑meetup</h3>
  <%= render "form" %>
</div>

app/views/groups/index.html.erb
<div class="col-md-12" style="margin-top:55px;">
<% if current_user %>
 <p>已经登入：你的 API token 是 <code><%= current_user.authentication_token  %></code></p>

<% end %>
</div>
<div class="col-md-12">

  <div class="group" style="margin-top:70px;">
    <%= link_to("创建 meetup",new_group_path, class: "btn btn-primary pull-right",style:"margin-bottom:20px;") %>

  </div>
  <table class="table  table-boldered table-striped custab table-hover">
    <thead>
      <tr>
        <td class="text-center">主题</td>
        <td class="text-center">内容</td>
        <td class="text-center">地点</td>
        <td class="text-center">参与人数</td>
        <td class="text-center">组织者</td>
        <td class="text-center">选项</td>
      </tr>
    </thead>
    <tbody>
      <% @groups.each do |group| %>
      <tr>
        <td class="text-center"><%=link_to(group.title, group_path(group)) %></td>
        <td class="text-center"><%= render_group_description(group) %></td>
        <td class="text-center"><%= group.city %></td>
        <td class="text-center">12</td>
        <!-- <td><%#= group.participate_users.count %></td> -->
        <!-- <td><%#= group.user %></td> -->
        <td class="text-center"><%= group.user.user_name %></td>
        <% if current_user && group.user == current_user %>
        <td class="text-center"><%= link_to("编辑",edit_group_path(group),class: "btn btn-sm btn-default") %>
            <%= link_to("取消",group_path(group), class:"btn btn-sm btn-default",method: :delete, data: {confirm: "确定取消该meetup?"}) %>
          </td>
          <%else  %>
          <td>

          </td>
          <%end %>


      </tr>
      <% end %>
    </tbody>
  </table>
</div>
<div class="text-center col-md-12">
  <%= will_paginate @groups, renderer: BootstrapPagination::Rails %>
</div>

app/views/groups/new.html.erb
<div class="col-md-4 col-md-offset-4">
  <h3 class="text-center">新建meetup</h3>
  <%= render "form" %>
</div>

app/views/groups/show.html.erb
  <div class="group" style="margin-top:75px;">
    <!-- <%# if current_user && @group.user == current_user %> -->
    <!-- <%#= link_to("编辑",edit_group_path(@group),class:"btn btn-primary pull-right") %> -->
    <!-- <%#end %> -->

  <h3>主题: <%= @group.title %></h3>
  活动内容: <p><%= render_group_description(@group) %></p>
  </div>
  <div class="col-md-6" style="margin-top:50px;">

    <%= simple_form_for [@group,@comment] do |f| %>
     <p>
       <%= f.input :review,label:"添加评论",input_html: { class: "form-area"},placeholder:"请写下你的评论"%>
     </p>
     <p>
       <%= f.submit "发表",class:"btn btn-sm btn-primary" %>
     </p>
       <% end %>
       <hr />

        <% if @group.comments.empty? %>
        <h3>0 条评论<h3>
          <hr>
          <% else %>
       <h3><%= @group.comments_count %>条评论</h3>
       <hr>
       <% @floor =1 %>

       <% @comments.each do |comment| %>
          <%= @floor %>楼
       <div class="comment clearfix">
       <%= simple_format(comment.review) %>
       <%= comment.user.user_name %>
       发表于<%=  time_ago_in_words(comment.created_at) %> 前
       <hr />
       </div>
        <% @floor = @floor + 1 %>
       <% end %>
       <% end %>

     <!-- <%#= render @group.comments %> -->
  </div>
  <div class="text-center col-md-12">
<%= will_paginate @comments, renderer: BootstrapPagination::Rails %>
  </div>